### ISSUE TITLE
Update sentiment analysis

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/irc-sentiment-bot#1]
Move from the naive implementation to https://github.com/cjhutto/vaderSentiment and translate the following:

* vader_lexicon.txt
* NEGATE words in the code
* BOOSTER words in the code
* SPECIAL_CASE_IDIOMS in the code

**Comment by AlexGustafsson** [comment]
The translation has been done and is available as https://github.com/AlexGustafsson/vaderSentiment-swedish.

**Comment by SpaceLenore** [comment]
Hi, I'd like to work on this. I'll submit a PR soon™.

**Comment by AlexGustafsson** [comment]
Closing as it's been fixed by @SpaceLenore.
